blank_issues_enabled: false
contact_links:
  - name: Private feedback and contact
    url: https://github.com/holleyk/ExperienceNorth-Feedback#private-feedback-and-contact
    about: Email contact@experiencenorth.ca for private questions or information.
